zshrc plugin 'github.com/zsh-users/zsh-syntax-highlighting'

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES+=(
    default                       'none'
    unknown-token                 'fg=red,bold'
    reserved-word                 'fg=yellow'
    alias                         'fg=green'
    builtin                       'fg=green'
    function                      'fg=green'
    command                       'fg=green,bold'
    precommand                    'fg=green,underline'
    commandseparator              'none'
    hashed-command                'fg=green'
    path                          'fg=cyan,underline'
    path_prefix                   'underline'
    path_approx                   'fg=yellow,underline'
    globbing                      'fg=blue'
    history-expansion             'fg=blue'
    single-hyphen-option          'none'
    double-hyphen-option          'none'
    back-quoted-argument          'none'
    single-quoted-argument        'fg=yellow'
    double-quoted-argument        'fg=yellow'
    dollar-double-quoted-argument 'fg=cyan'
    back-double-quoted-argument   'fg=cyan'
    assign                        'none'
    bracket-error                 'fg=red,bold'
    bracket-level-1               'fg=blue,bold'
    bracket-level-2               'fg=green,bold'
    bracket-level-3               'fg=magenta,bold'
    bracket-level-4               'fg=yellow,bold'
    bracket-level-5               'fg=cyan,bold'
    cursor-matchingbracket        'standout'
)
